GET http://localhost:8080/api/code/e5768dcf-5f90-4093-9293-b08ef0b6a3b4
Accept: application/json

###
GET http://localhost:8080/api/code/latest
Accept: application/json

###
//none limited code
POST http://localhost:8080/api/code/new
Content-Type: application/json

{
  "code": "not limited",
  "time": 0,
  "views": 0
}
###
//none limited code
POST http://localhost:8080/api/code/new
Content-Type: application/json

{
  "code": "not limited",
  "time": -5,
  "views": -5
}
###
//limited code
POST http://localhost:8080/api/code/new
Content-Type: application/json

{
  "code": "limited",
  "time": 20,
  "views": 0
}

###